<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "profile".
 *
 * @property int $id
 * @property string $full_name
 * @property string $national_card
 * @property string $conractor
 * @property string $signature_certificate
 * @property file $file_one
 * @property file $file_tow
 * @property file $file_tree
 * @property int $created_at
 * @property int $updated_at
 */
class Profile extends \yii\db\ActiveRecord
{
    public $file_one;
    public $file_tow;
    public $file_tree;
    /**
     * {@inheritdoc}
     */

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    public static function tableName()
    {
        return 'profile';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['full_name', 'national_card', 'conractor', 'signature_certificate', 'created_at', 'updated_at','file_one','file_tow','file_tree'], 'required'],
            [['created_at', 'updated_at'], 'integer'],
            [['full_name', 'national_card', 'conractor', 'signature_certificate'], 'string', 'max' => 100],
            [['file_one','file_tow','file_tree'],'file','extensions'=>'jpg,png,pdf']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'full_name' => Yii::t('app', 'Full Name'),
            'national_card' => Yii::t('app', 'National Card'),
            'conractor' => Yii::t('app', 'Conractor'),
            'signature_certificate' => Yii::t('app', 'Signature Certificate'),
            'file_one' => Yii::t('app', 'File One'),
            'file_tow' => Yii::t('app', 'File Tow'),
            'file_tree' => Yii::t('app', 'File Tree'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }
    public function beforeSave($insert)
    {
        $this->created_at = time();
        $this->updated_at = time();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
